---

- name: make smart_note directory
  file:
    dest: /home/deploy/apps/smart_note
    state: directory
  become: yes
  become_user: deploy

- name: make current directory
  file:
    dest: /home/deploy/apps/smart_note/current
    state: directory
  become: yes
  become_user: deploy

- name: make releases directory
  file:
    dest: /home/deploy/apps/smart_note/releases
    state: directory
  become: yes
  become_user: deploy

- name: make shared directory
  file:
    dest: /home/deploy/apps/smart_note/shared
    state: directory
  become: yes
  become_user: deploy

- name: copy systemd file
  copy:
    src: smart_note.service
    dest: /etc/systemd/system/smart_note.service
  become: yes
  notify: reload systemd

# This is edited on the server now, let's not re-template
- name: copy config file
  when: release_env == "local"
  copy:
    src: "{{ vapor_file }}"
    dest: /etc/smart_note.env
  become: yes

- name: enable smart_note service
  systemd:
    name: smart_note.service
    enabled: yes
  become: yes
